#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 512
#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32
#define BLOCK_SIZE ((WINDOW_HEIGHT) / (DISPLAY_HEIGHT))

enum { SYS_COSMAC_VIP, SYS_S_CHIP, SYS_AMIGA };
#define SYS_TYPE SYS_S_CHIP

#define CHIP8_NO_CYCLES 700.0;

#endif
